# Sample workflow for building and deploying a Next.js site to GitHub Pages
# Triggers on push to main branch and manual dispatch
#
# To get started with Next.js see: https://nextjs.org/docs/getting-started
#
name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: npm
          
      - name: Clean install dependencies
        run: |
          npm ci
          npm install sharp --force
          
      - name: Clean and Build
        run: |
          npm run clean
          npm run build
        env:
          NODE_ENV: production
          NEXT_TELEMETRY_DISABLED: 1
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: gh-pages
          force_orphan: true
          cname: # optional
          enable_jekyll: false
          allow_empty_commit: false
          keep_files: false
          commit_message: "Deploy Next.js site to Pages"
